default_config:
# For homeassistant v2021.7.0 and above add this http block
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.79 # Add the IP address of the proxy server
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.79:3218/
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://192.168.1.79:1880/
    require_admin: true
mqtt:

recorder:
  db_url: mysql://homeassistant:ha_dbdatabasepassword@192.168.1.79/ha_db?charset=utf8
  purge_keep_days: 30
